In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/RayCarpenterIII/Measuring-Race-Ethnicity-and-Gender-Gaps-in-Mortgage-Approvals/main/2019_HMDA_sample.csv')

In [3]:
df

,activity_year,lei,derived_msa-md,state_code,county_code,census_tract,conforming_loan_limit,derived_loan_product_type,derived_dwelling_category,derived_ethnicity,...,denial_reason-2,denial_reason-3,denial_reason-4,tract_population,tract_minority_population_percent,ffiec_msa_md_median_family_income,tract_to_msa_income_percentage,tract_owner_occupied_units,tract_one_to_four_family_homes,tract_median_age_of_housing_units
0,2019,5493000YNV8IX4VD3X12,99999,KY,21187.0,2.118797e+10,C,Conventional:First Lien,Single Family (1-4 Units):Manufactured,Not Hispanic or Latino,...,NaN,NaN,NaN,3297,5.58,49800,135,1007,1471,31
1,2019,549300O6Z0I6KYMESL47,16984,IL,17031.0,1.703181e+10,C,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Hispanic or Latino,...,NaN,NaN,NaN,4279,39.10,82000,112,1331,1484,57
2,2019,549300XRXBA38J60S618,99999,ID,16039.0,1.603996e+10,C,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,...,NaN,NaN,NaN,2570,22.49,57100,89,854,1916,39
3,2019,549300NBFJM2PBH24L77,48620,KS,20173.0,2.017301e+10,C,Conventional:First Lien,Single Family (1-4 Units):Manufactured,Not Hispanic or Latino,...,NaN,NaN,NaN,5346,20.50,69500,126,1667,1904,24
4,2019,C5654JQHZUHN0772B561,47894,VA,51683.0,5.168391e+10,C,VA:First Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,...,NaN,NaN,NaN,5854,51.81,114700,76,1025,1355,29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2019,254900FL0I8OUMMBOZ11,38060,AZ,4013.0,4.013072e+09,C,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Ethnicity Not Available,...,NaN,NaN,NaN,3031,8.02,72900,65,1701,2620,49
96,2019,549300NOCASXPA34X033,15180,TX,48061.0,4.806101e+10,C,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Ethnicity Not Available,...,NaN,NaN,NaN,7046,90.41,44000,123,1686,2246,32
97,2019,B4TYDEB6GKMZO031MB27,22744,FL,12011.0,1.201104e+10,C,Conventional:Subordinate Lien,Single Family (1-4 Units):Site-Built,Ethnicity Not Available,...,NaN,NaN,NaN,4961,25.06,68600,173,1389,1705,49
98,2019,549300CY7WNAHKHYSJ73,99999,WA,53037.0,5.303798e+10,NC,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,...,NaN,NaN,NaN,4562,5.09,63500,110,1412,2038,20
99,2019,549300YOESI1GLKRL151,16740,SC,45091.0,4.509106e+10,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Ethnicity Not Available,...,NaN,NaN,NaN,5616,42.50,70700,76,1082,1860,39

In [5]:
df.to_csv('2019 HMDA Sample.csv', index=False)